### ISSUE TITLE
v1.3: Technical name of dangerous goods mandatory while optional field

### ISSUE THREAD

**Issue by joeri-jansen** [cesniti/erinot_xsd#2]
The correct technical name of a dangerous good is mandatory in the XSD. However, this is an optional field (only required for some goods).

**Comment by jverstichel** [comment]
TechnicalName has been present as a mandatory field for Dangerous Goods since (at least) version 1.2e (included in ERI GUIDE 2.0).
It matches to 'Name of dangerous good (proper shipping name)' in the EDIFACT, which is in fact a mandatory field. (see picture below).

![image](https://user-images.githubusercontent.com/71881553/132370925-8b0958df-6a46-4bbe-867a-43c86bb8fc14.png)


Therefore I believe this is correctly implemented, unless I am missing something?

**Comment by joeri-jansen** [comment]
We concluded the following, together with Rijkswaterstaat: 
the Edifact 'Name of dangerous good (propper shipping name)' matches the 'propper shipping name' in the XSD.
the Edifact 'Correct Technical name' matches the 'technical name' in the XSD. The 'Correct technical name' is not mandatory in EDIFACT (and opposes us with an issue when filling the XML: we do not always have something to fill in).
![image](https://user-images.githubusercontent.com/90042688/132372968-c14d36c1-c4c9-416b-af63-4ac7f0443e2a.png)

**Comment by joeri-jansen** [comment]
For now, we could use the workaround to leave the technical name element empty if no technical name is present in our data. According to the XSD, this is allowed.
